burning-airlines-server/config/routes.rb
Rails.application.routes.draw do
 
  
  root to: 'dashboard#app'
  resources :airplanes, :flights, :reservations, :users

  get '/details' => 'reservation#details'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  get '/find/:name' => 'users#find'


end

burning-airlines-server/app/models/airplane.rb
class Airplane < ApplicationRecord

    has_many :flights

end #end Airplane

burning-airlines-server/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

burning-airlines-server/app/models/flight.rb
class Flight < ApplicationRecord

    belongs_to :airplane, optional: true
    has_many :reservations
    has_many :users, through: 'reservations'

end

burning-airlines-server/app/models/reservation.rb
class Reservation < ApplicationRecord

    belongs_to :user, optional: true
    belongs_to :flight, optional: true
    
end

burning-airlines-server/app/models/user.rb
class User < ApplicationRecord

    validates :name, length: {minimum: 2}, uniqueness: true

    validates :email, presence: true, uniqueness: true

    has_secure_password

    has_many :reservations
    has_many :flights, through: 'reservations'

end

burning-airlines-server/app/controllers/airplanes_controller.rb
class AirplanesController < ApplicationController

  before_action :check_if_logged_in, except: [:index, :show]
  
  def new
    @airplane = Airplane.new
  end

  def create
    @airplane = Airplane.create airplane_params

    redirect_to airplanes_path
  end

  def index
    @airplanes = Airplane.all
    respond_to do |format|
      format.html #shows page as html
      format.json {render json: @airplanes} #shows json
    end
  end

  def show
    @airplane = Airplane.find params[:id]
  end

  def edit
  end

  def update
    
  end

  private 

  def airplane_params
    params.require(:airplane).permit(:name, :row, :column)
  
  end



end

burning-airlines-server/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :fetch_user

    def fetch_user

        if session[:user_id].present?
            @current_user = User.find_by id:session[:user_id]
        end # login check

        unless @current_user.present?
            session[:user_id] = nil
        end

    end # login check


    def check_if_logged_in

        if !@current_user.present? || !@current_user.admin
            flash[:error] = 'You must be logged in to perform that action'
            redirect_to login_path
        end

    end # check_if_logged_in


end # class ApplicationController

burning-airlines-server/app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def app
    

  end
end

burning-airlines-server/app/controllers/flights_controller.rb
class FlightsController < ApplicationController

  before_action :check_if_logged_in, except: [:index, :show]

  def new
    @flight = Flight.new
  end

  def create
    @flight = Flight.create flight_params
        if @flight.persisted? 
            render json: @flight #send the created flight object as JSON response
        else
            render json: { error: 'Could not create flight' }, status: 422 #'Unprocessable Entity'
        end #end if
  end

  def index
    @flights = Flight.all
    respond_to do |format|
      format.html #shows page as html
      format.json {render json: @flights} #shows json
    end


  end

  def show
    # @flight = Flight.find_by params[:flight_number]
    @flight = Flight.find_by flight_number: params[:id]
    respond_to do |format|
      format.html #shows page as html
      format.json {render json: @flight, include: [:users, :airplane, :reservations]} 
    end
    
  end

  def edit
  end

  def update
  end

  private

  def flight_params
    params.require(:flight).permit(:date, :origin, :destination, :flight_number, :airplane_id )

  end 


end

burning-airlines-server/app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  skip_before_action :verify_authenticity_token, raise: false

  before_action :check_if_logged_in, except: [ :show, :create]
  

  def details #trialling a custom route to get complete informaiton

  
  end

  def new
    @reservation = Reservation.new
  end

  def create
    @reservation = Reservation.create reservation_params
    
  end

  def index
    @reservations = Reservation.all.reverse

    # @reservations.each do |r| 
    #   {
    #     row: r.row,
    #     column: r.column,
    #     user: r.user.name,
    #     origin: r.flight.origin,
    #     destination: r.flight.destination,
    #     date: r.flight.date,
    #     airplane: r.flight.airplane.name
    #   }
    # end

    respond_to do |format|
      format.html #shows page as html
      format.json {render json: @reservations, include: [:user, :flight]} #shows json
    end

  end

  def show
    @reservation = Reservation.last
    respond_to do |format|
      format.html #shows page as html
      format.json {render json: @reservation, include: [:user, :flight]} #shows json
    end

  end

  def edit
    @reservation = Reservation.find params[:id]
  end

  def update
    @reservation = Reservation.find params[:id]

  end

  private

  def reservation_params
    params.require(:reservation).permit(:row, :column, :user_id, :flight_id)
  end


end

burning-airlines-server/app/controllers/session_controller.rb
class SessionController < ApplicationController

  #Login
  def new
  end

  def create

    user = User.find_by email: params[:email]

    if user.present? && user.authenticate(params[:password])

      session[:user_id] = user.id
      redirect_to root_path

    else

      flash[:error] = 'Invalid email address or password'
      redirect_to login_path

    end # if

  end #create

  # Logout
  def destroy
    session[:user_id] = nil
    redirect_to login_path

  end

end

burning-airlines-server/app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :check_if_logged_in, except: [:new, :create, :index, :show, :find]

  def new
    @user = User.new
  end

  def create
    @user = User.create user_params

    if @user.persisted?
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      render :new
    end # if

  end # create

  def index
    @users = User.all
  end

  def find #a custom route 
    @user = User.find_by name: params[:name]
    respond_to do |format|
      format.html #shows page as html
      format.json {render json: @user}
    end
  end

  def show
    @user = User.find params[:id]
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def user_params
    params.require(:user).permit(:name, :admin, :email, :password, :password_confirmation)
  end



end # class UsersController

burning-airlines-server/app/helpers/airplanes_helper.rb
module AirplanesHelper
end

burning-airlines-server/app/helpers/application_helper.rb
module ApplicationHelper
end

burning-airlines-server/app/helpers/dashboard_helper.rb
module DashboardHelper
end

burning-airlines-server/app/helpers/flights_helper.rb
module FlightsHelper
end

burning-airlines-server/app/helpers/reservations_helper.rb
module ReservationsHelper
end

burning-airlines-server/app/helpers/session_helper.rb
module SessionHelper
end

burning-airlines-server/app/helpers/users_helper.rb
module UsersHelper
end

burning-airlines-server/app/views/airplanes/_form.html.erb
<div class = "beCenter">
<div class="form" >
    <% if @airplane != nil %>
        <% if @airplane.errors.any? %>
            <strong>Please corrrect the following:</strong>
            <ul>
                <% @airplane.errors.full_messages.each do |e| %>
                    <li><%= e %></li>

                <% end %>
            </ul>
        <% end  %>
     <% end  %>
</div>
</div>

<div class = "beCenter">
    <%= form_with model: @airplane, local: true do |f| %>

        
        <%= f.text_field :name, placeholder:'What is the name of this plane?' %>
        <br>
        
        <%= f.text_field :row, placeholder:'How many ROWS (#) are there?' %>
        <br>
        <%= f.text_field :column, placeholder:'How many COLUMNS (A-E) are there?' %>
        <br>
        <%= f.label :total_seats %>
        <%= f.number_field :total_seats %>
        <br>
    
        

        <%= f.submit class:"button"%>
    <% end %>

</div>

burning-airlines-server/app/views/airplanes/create.html.erb
<h1>Airplanes#create</h1>
<p>Find me in app/views/airplanes/create.html.erb</p>

burning-airlines-server/app/views/airplanes/edit.html.erb
<h1>Airplanes#edit</h1>
<p>Find me in app/views/airplanes/edit.html.erb</p>

burning-airlines-server/app/views/airplanes/index.html.erb
<div class = "beCenter">
<h2>All Airplanes</h2>
</div>

<div class = "beCenter">
<% if @current_user.present? && @current_user.admin %>
    <%= link_to 'Add Plane', new_airplane_path %>
<% end %>
</div>

<% @airplanes.each do |plane|  %> 
<div class = "beCenter">

    <%= link_to plane.name, airplane_path(plane.id) %></p>
    <ul>
        <li>Total row /column:<%= plane.row %> <%= plane.column %></li>
        <li>Total number of seats: <%= plane.total_seats %></li>
    
    </ul>
    
</div>
<% end %>

burning-airlines-server/app/views/airplanes/new.html.erb
<div class = "beCenter">
<h2>Add new plane</h2>
</div>

<%= render partial: "form" %>

burning-airlines-server/app/views/airplanes/show.html.erb
<div class="beCenter">
    <h2>Viewing Details for <%=  @airplane.name %></h2>
    <br/>
    <p>Total Seats: <%= @airplane.total_seats %>


</div>

burning-airlines-server/app/views/airplanes/update.html.erb
<h1>Airplanes#update</h1>
<p>Find me in app/views/airplanes/update.html.erb</p>

burning-airlines-server/app/views/dashboard/app.html.erb
<% if @current_user.present? && @current_user.admin %>
<div class = "beCenter">
    <h2>Welcome back to BURNING Airlines, Admin</h2>
</div>

   <div class = "beCenter">
        <%= render partial: '/airplanes/form' %>
    </div>

<% else %>
<div class = "beCenter">
    <h2>Welcome to BURNING Airlines</h2>
</div>


<div class = "beCenter">
    <%= image_tag "concorde.jpg" ,alt: "burning airlines", class: "airline_image" %>
</div>

<% end %>

burning-airlines-server/app/views/flights/_form.html.erb
<div class = "beCenter">
<div class="flights" id="new_flight_form">
    <% if @flight != nil %>
        <% if @flight.errors.any? %>
            <strong>Please corrrect the following:</strong>
            <ul>
                <% @flight.errors.full_messages.each do |e| %>
                    <li><%= e %></li>

                <% end %>
            </ul>

        <% end  %>
    <% end   %>
</div>

<div class = "beCenter">
    <%= form_with model: @flight, local: true do |f| %>

        
        <%= f.date_field :date %>
        <br><br>
        
        <%= f.text_field :origin, placeholder:'Enter Origin' %>
        <br><br>
        
        <%= f.text_field :destination, placeholder:'Enter Destination' %>
        <br><br>
        
        <%= f.label :flight_number, 'FlightNumber'  %>
        <br>
        <%= f.number_field :flight_number %>
        <br><br>

        <%= f.submit class:"button"%>
    <% end %>
</div>
</div>

burning-airlines-server/app/views/flights/create.html.erb
<h1>Flights#create</h1>
<p>Find me in app/views/flights/create.html.erb</p>

burning-airlines-server/app/views/flights/edit.html.erb
<h1>Flights#edit</h1>
<p>Find me in app/views/flights/edit.html.erb</p>

burning-airlines-server/app/views/flights/index.html.erb
<div class = "beCenter">
<h2>All flights</h2>
</div>

<div class = "beCenter">
<% if @current_user.present? && @current_user.admin %>
    <%= link_to 'Add New Flight', new_flight_path %>
<% end %>
</div>

<div class = "beCenter">
<p> Date - Origin  - Destination - Plane - Flight#
</div>


<% @flights.each do |flight|  %> 
<div class = "beCenter">
    <p><%= flight.date %> &nbsp;&nbsp;&nbsp;&nbsp;
     <%= flight.origin %> &nbsp;&nbsp;&nbsp;&nbsp;
      <%= flight.destination %> &nbsp;&nbsp;&nbsp;&nbsp;
      <%= flight.airplane.name %> &nbsp;&nbsp;&nbsp;&nbsp;

        <a href="<%= "http://localhost:3001/#/flights/"+ flight.flight_number.to_s %>"><%= flight.flight_number %></a>
</div>

<% end %>

burning-airlines-server/app/views/flights/new.html.erb
<div class = "beCenter">
<h2>Add new Flight</h2>
</div>


<%= render partial: 'form' %>

burning-airlines-server/app/views/flights/show.html.erb
<h1>Flights#show</h1>
<p>Find me in app/views/flights/show.html.erb</p>

burning-airlines-server/app/views/flights/update.html.erb
<h1>Flights#update</h1>
<p>Find me in app/views/flights/update.html.erb</p>

burning-airlines-server/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BurningAirlinesServer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>


  <body>
    <header>
    <div class = "beCenter">
      <h1>Welcome to Burning Airlines</h1>
    </div>

    <div class = "beCenter">
      <% if @current_user.present? %>
        Welcome, <%= @current_user.name %>
        &nbsp;&nbsp;&nbsp;&nbsp;    
        <%= link_to 'Logout', login_path, method: 'delete' %>
        &nbsp;&nbsp;&nbsp;&nbsp;
      <% else %>
        <%= link_to 'Login', login_path %>
        &nbsp;&nbsp;&nbsp;&nbsp;
        <%= link_to 'Sign up', new_user_path %>
        &nbsp;&nbsp;&nbsp;&nbsp;
      <% end %>



      <%= link_to 'Home', root_path %>
      &nbsp;&nbsp;&nbsp;&nbsp;
      <%= link_to 'All Flights', flights_path %>
      &nbsp;&nbsp;&nbsp;&nbsp;
      <%= link_to 'All Airplanes', airplanes_path %>
      &nbsp;&nbsp;&nbsp;&nbsp;

      <% if @current_user.present? && @current_user.admin %>
        <%= link_to 'All Reservations', reservations_path %>
      <% end %>
    
    </div>
    </header>

    <%= yield %>
  </body>

</html>

burning-airlines-server/app/views/reservations/_form.html.erb
<div class = "beCenter">
<div class="reservations" id="new_reservation_form">
    <% if @reservation != nil %>
        <% if @reservation.errors.any? %>
            <strong>Please corrrect the following:</strong>
            <ul>
                <% @reservation.errors.full_messages.each do |e| %>
                    <li><%= e %></li>

                <% end %>
            </ul>

        <% end  %>
    <% end   %>
</div>


<div class = "beCenter">
    <%= form_with model: @reservation, local: true do |f| %>

        
        <%= f.text_field :row, placeholder:'Enter row' %>
        <br>
        
        <%= f.text_field :column, placeholder:'Enter column' %>
        <br>

        <%= f.submit class:"button"%>
    <% end %>
</div>

burning-airlines-server/app/views/reservations/create.html.erb
<h1>Reservations#create</h1>
<p>Find me in app/views/reservations/create.html.erb</p>

burning-airlines-server/app/views/reservations/edit.html.erb
<h1>Reservations#edit</h1>
<p>Find me in app/views/reservations/edit.html.erb</p>

burning-airlines-server/app/views/reservations/index.html.erb
<div class = "beCenter">
<h2>All Reservations</h2>
</div>

<div class = "beCenter">
<% if @current_user.present? %>
    <%= link_to 'New Reservations', new_reservation_path %>
<% end %>
</div>


<% @reservations.each do |r|  %> 
<div class = "beCenter">
<div class = "reservationBox">
<ul>
    <li><%= r.row %> <%= r.column %></li>

    <li>Booked by <%= r.user.name %></li>

    <li><%= r.flight.origin%> >> <%= r.flight.destination %> on <%=r.flight.date %></li>

    <li>flying by <%= r.flight.airplane.name%></li>
</ul>

</div>
</div>

<% end %>


<%= @allDate %>

burning-airlines-server/app/views/reservations/new.html.erb
<div class = "beCenter">
<h2>Add new Reservation</h2>
</div>

<%= render partial: 'form' %>

burning-airlines-server/app/views/reservations/show.html.erb
<h1>Reservations#show</h1>
<p>Find me in app/views/reservations/show.html.erb</p>

burning-airlines-server/app/views/reservations/update.html.erb
<h1>Reservations#update</h1>
<p>Find me in app/views/reservations/update.html.erb</p>

burning-airlines-server/app/views/session/new.html.erb
<div class = "beCenter">
    <h2>Login</h2>
</div>

<div class = "beCenter">
    <% if flash[:error] %>

        <br>
        <strong>
            <%= flash[:error] %>
        </strong>
        <br><br>

    <% end %>
</div>

<div class = "beCenter">
    <%= form_with url:login_path, local: true do |f| %>

        <%= f.label :email, 'Email Address' %>
        <br>
        <%= f.text_field :email %>
        <br><br>

        <%= f.label :password %>
        <br>
        <%= f.password_field :password %>
        <br><br>

        <%= f.submit 'Login' %>

    <% end %>
</div>

burning-airlines-server/app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

burning-airlines-server/app/views/users/new.html.erb
<div class = "beCenter">
<h2>Sign up</h2>
</div>

<div class = "beCenter">
<% if @user.errors.any? %>
    <strong>Please correct the following errors: </strong>
    <ul>
        <% @user.errors.full_messages.each do |e| %>
            <li><%= e %></li>
        <% end %>
    </ul>

<% end %>
</div>

<div class = "beCenter">
<%= form_with model: @user, local: true do |f| %>

    <div class= "user_form_block">
    <%= f.label :name %>
    <br>
    <%= f.text_field :name %>
    </div>


    <div class= "user_form_block">
    <%= f.label :email %>
    <br>
    <%= f.text_field :email %>
    </div>


    <div class= "user_form_block">
    <%= f.label :password %>
    <br>
    <%= f.password_field :password %>
    </div>


    <div class= "user_form_block">
    <%= f.label :password_confirmation %>
    <br>
    <%= f.password_field :password_confirmation %>
    </div>


    <div class= "user_form_block">
    <%= f.submit %>
    </div>



<% end %>
</div>

burning-airlines-server/app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>